//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "book_checkouts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub checkout_id: Uuid,
    pub book_id: Uuid,
    pub checked_out_at: DateTimeWithTimeZone,
    pub checked_out_by_id: Uuid,
    pub checked_out_by_name: String,
    pub returned_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "book_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub books: HasOne<super::books::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
