//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "books")]
pub struct Model {
    pub title: String,
    pub isbn: Option<String>,
    pub description: Option<String>,
    pub owner_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub created_by_id: Uuid,
    pub created_by_name: String,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub updated_by_id: Option<Uuid>,
    pub updated_by_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::book_authors::Entity")]
    BookAuthors,
    #[sea_orm(has_many = "super::book_checkouts::Entity")]
    BookCheckouts,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::book_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookAuthors.def()
    }
}

impl Related<super::book_checkouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookCheckouts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        super::book_authors::Relation::Authors.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::book_authors::Relation::Books.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
