//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "books")]
pub struct Model {
    pub title: String,
    pub isbn: Option<String>,
    pub description: Option<String>,
    pub owner_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub created_by_id: Uuid,
    pub created_by_name: String,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub updated_by_id: Option<Uuid>,
    pub updated_by_name: Option<String>,
    #[sea_orm(has_many)]
    pub book_authors: HasMany<super::book_authors::Entity>,
    #[sea_orm(has_many)]
    pub book_checkouts: HasMany<super::book_checkouts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
