//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::authors::Entity as Authors;
pub use super::book_authors::Entity as BookAuthors;
pub use super::books::Entity as Books;
pub use super::users::Entity as Users;
